name: build-test-release-windows

on:
  [workflow_dispatch, pull_request]


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "VCPKG_DEFAULT_BINARY_CACHE=C:/vcpkg_cache" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        with:
          path: C:/vcpkg_cache
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Upgrade LLVM
        run: |
            choco uninstall llvm -y
            choco install llvm -y
            echo "C:\Program Files\LLVM\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
    
      - name: Reset vcpkg to required version
        run: |
          cd C:/vcpkg
          git fetch origin
          git checkout d5ec528843d29e3a52d745a64b469f810b2cedbf
          .\bootstrap-vcpkg.bat
    
      - name: Install dependencies with vcpkg
        run: |
          mkdir C:\vcpkg_cache -ErrorAction SilentlyContinue
          cd $env:GITHUB_WORKSPACE  # Ensure we are in the project directory
          echo "VCPKG_FEATURE_FLAGS=manifests" | Out-File -FilePath $env:GITHUB_ENV -Append
          C:/vcpkg/vcpkg.exe install --recurse

      - name: Configure CMake
        run: |
            cmake -B build -S . `
                -G "Visual Studio 17 2022" `
                -T ClangCL `
                -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
                -DCMAKE_C_COMPILER=clang `
                -DCMAKE_CXX_COMPILER=clang++ `
                -DCMAKE_CXX_FLAGS="/utf-8 /EHsc" `
                -DCMAKE_BUILD_TYPE=Release `
                -DBUILD_FRONTEND=ON
    
      - name: List build directory contents
        run: |
            echo "---- Build Directory Contents ----"
            Get-ChildItem -Path build -Recurse | Format-Table -AutoSize

      - name: Build Project
        run: |
          cmake --build build --config Release
      
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: NES-Emulator-Build
          path: build/