# This workflow performs linting and formatting checks based on
# our defined clang-format and clang-tidy configurations.

# The workflow is triggered on pull requests and checks for changes in C++ files.
# If changes are detected, the workflow installs grabs the latest
# Docker container, and runs linting/formatting tests.

# If the checks pass, the workflow will report success. If the checks fail,
# the workflow will report failure.

name: lint-format-test

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'
        type: string
      commit:
        description: 'Shortform commit hash to build'
        required: false
        default: 'HEAD'
        type: string

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      
      - name: Get specified commit
        if: ${{ github.event.inputs.commit != 'HEAD' }}
        run: |
          git checkout ${{ github.event.inputs.commit }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/coopeaus/nes-emulator/build-lint-container:latest

      - name: Run Linter
        run: |
          # Build and lint
          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            build

          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            lint

      - name: Run Nestest ROM
        run: |
          touch ./tests/output/my_nestest-log.txt
          chmod ugo+rw ./tests/output/my_nestest-log.txt

          # Test, using the build from before
          docker run -e CI=${CI} \
            --rm -v "$(pwd):/workspace" \
            -v build:/workspace/build \
            -v docker-vcpkg:/workspace/docker-vcpkg \
            -w /workspace ghcr.io/coopeaus/nes-emulator/build-lint-container:latest \
            test "RomTests.Nestest"
