name: test-build-mac-arm

on:
    pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up environment variables
        run: |
          echo "VCPKG_DEFAULT_BINARY_CACHE=/tmp/vcpkg_cache" >> $GITHUB_ENV
          echo "VCPKG_ROOT=/tmp/vcpkg" >> $GITHUB_ENV
  
      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/vcpkg_cache
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Get missing tools
        run: |
          brew update
          brew install llvm cmake pkg-config ninja
    
      - name: Update clang and clang++ references on PATH
        run: |
          echo "/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_PATH
    
      - name: Check dependencies
        run: |
          chmod ugo+x ./scripts/env-check.sh
          ./scripts/env-check.sh
        continue-on-error: true
        
      - name: Checkout pinned version of vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git /tmp/vcpkg
          cd /tmp/vcpkg
          git fetch
          git checkout d5ec528843d29e3a52d745a64b469f810b2cedbf
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Install dependencies with vcpkg
        run: |
          mkdir /tmp/vcpkg_cache -p
          cd $GITHUB_WORKSPACE
          echo "VCPKG_FEATURE_FLAGS=manifests" >> $GITHUB_ENV
          /tmp/vcpkg/vcpkg install --recurse

      - name: Build Project
        run: |
          chmod ugo+x ./scripts/env-check.sh
          chmod ugo+x ./scripts/build.sh
          ./scripts/env-check.sh
          ./scripts/build.sh
      
      - name: Copy files to Release directory
        run: |
          cp -r build/fonts build/Release/
          cp -r build/palettes build/Release/
          cp -r build/tests build/Release/
  
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: macOS-arm64
          path: build/Release